### ISSUE TITLE
context_words flag not working

### ISSUE THREAD

**Issue by frnowak** [openredact/nerwhal#10] opened 2021-04-22 11:45 UTC
Dear OpenRedact Team,

I am working on an `ubuntu 20.04` machine with `nerwhal 0.1.1` installed in a virtual env via `pip`. The code is run in a `jupyter notebook`. I was generally following the Usage instructions from the Readme, but I run into a KeyError when switching on the `context_words` flag (runs fine if setting it to False):
```python
recognizers = nerwhal.list_integrated_recognizers()
rconfig = nerwhal.Config(
    language="de",
    use_statistical_ner=True,
    recognizer_paths=recognizers
)
result = nerwhal.recognize(
    text,
    config=rconfig,
    combination_strategy="smart-fusion",
    context_words=True,
    return_tokens=False,
) 
```
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-46-b780c40150ac> in <module>
----> 1 results = [
      2     nerwhal.recognize(
      3         wrapper.text,
      4         config=rconfig,

<ipython-input-46-b780c40150ac> in <listcomp>(.0)
      1 results = [
----> 2     nerwhal.recognize(
      3         wrapper.text,
      4         config=rconfig,

path/to/nerwhal/core.py in recognize(text, config, combination_strategy, context_words, return_tokens)
    140             )
    141             sentence_words = [token.text for token in sentence_tokens]
--> 142             context_words = analyzer.recognizer_lookup[ent.recognizer].CONTEXT_WORDS
    143             if any(word in sentence_words for word in context_words):
    144                 ent.score = min(ent.score * analyzer.config.context_word_confidence_boost_factor, 1.0)

KeyError: 'StanzaNerBackend'
```
Adding stanza by hand leads to package not found:

```python
recognizers.append('path/to/nerwhal/backends/stanza_ner_backend.py')
```
```
...
path/to/backends/stanza_ner_backend.py in <module>
----> 1 from .base import Backend
      2 from nerwhal.types import NamedEntity
      3 from nerwhal.nlp_utils import load_stanza_nlp
      4 
      5 # the stanza NER models have an F1 score between 74.3 and 94.8, https://stanfordnlp.github.io/stanza/performance.html

ImportError: attempted relative import with no known parent package
```

Do I miss something?

**Comment by langhabel** [comment] 2021-05-23 08:40
Thanks a lot for your bug report. The issue is fixed in 0.1.2.

Currently, the statistical recognizer StanzaNerBackend is behaving differently than the other recognizers. Most notably for you is that entities found by it can't be linked with context words yet.

**Closed by langhabel** 2021-05-23 08:40 UTC
